
IF OBJECT_ID('dbo.TEST_STORE_LAST_UPDATE_OnlineSale', 'U') IS NOT NULL
    DROP TABLE dbo.TEST_STORE_LAST_UPDATE_OnlineSale;
GO

CREATE TABLE dbo.TEST_STORE_LAST_UPDATE_OnlineSale
(
    DATE_LAST_UPDATE DATETIME 
);

INSERT INTO dbo.TEST_STORE_LAST_UPDATE_OnlineSale (DATE_LAST_UPDATE)
VALUES ('2011-05-30');  -- or any starting point

IF OBJECT_ID('dbo.TEST_STORE_LAST_UPDATE_StoreSale', 'U') IS NOT NULL
    DROP TABLE dbo.TEST_STORE_LAST_UPDATE_StoreSale;
GO
CREATE TABLE dbo.TEST_STORE_LAST_UPDATE_StoreSale
(
    DATE_LAST_UPDATE DATETIME 
);

INSERT INTO dbo.TEST_STORE_LAST_UPDATE_StoreSale (DATE_LAST_UPDATE)
VALUES ('2011-05-30');

------------------------------------
SELECT * FROM dbo.TEST_STORE_LAST_UPDATE_StoreSale
SELECT * FROM dbo.TEST_STORE_LAST_UPDATE_OnlineSale

UPDATE [AdventureWorks2022].dbo.TEST_STORE_LAST_UPDATE_StoreSale
SET DATE_LAST_UPDATE = '2011-05-30';

UPDATE [AdventureWorks2022].dbo.TEST_STORE_LAST_UPDATE_OnlineSale
SET DATE_LAST_UPDATE = '2011-05-30';
